name: mirror
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+63

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # 网络请求
  dio: ^4.0.0
  # 数据状态管理
  provider: ^5.0.0
  # sqlite数据库
  sqflite: ^2.0.0+3
  # 处理权限
  permission_handler: ^8.0.1
  # 本地媒体库
  photo_manager: ^1.2.2
  # 融云IM
  rongcloud_im_plugin: ^5.1.2
  # 七牛上传库
  sy_flutter_qiniu_storage: ^0.2.1
  # 路由管理
  fluro: ^2.0.3
  # 富文本
  rich_text_widget: ^0.2.5
  # 下方弹出抽屉
  sliding_up_panel: ^2.0.0+1
  # 轮播图插件
  flutter_swiper: ^1.1.6
  # 区分设备
  device_info: ^2.0.2
  # 列表交错动画
  flutter_staggered_animations: ^1.0.0
  # 页面过渡动画此暂时运用到图片过渡
  animations: ^2.0.0
  # ListView滚动插件
  scroll_to_index: ^2.0.0
  # 网络图片缓存
  cached_network_image: ^3.0.0
  # tarBar嵌套Tarbar联动
  union_tabs: ^1.0.0+7
  #  extended_tabs
  # 输入框内富文本显示
#  text_span_field: ^2.0.6
  # 文件路径
  path_provider: ^2.0.2
  # 视频播放器 暂时先用着系统自带的这个
  video_player: ^2.1.5
  # 声网直播引擎
  agora_rtc_engine: '3.2.1'
  # 相机
  camera: ^0.5.8+11
  #系统日历工具
  device_calendar: ^3.1.0
  # 直播播放器 https://fijkplayer.befovy.com/
  fijkplayer: ^0.8.8
  # 下拉刷新上拉加载
  pull_to_refresh: ^2.0.0
  # shared preferences
  shared_preferences: ^2.0.6
  # 汉字转拼音
  lpinyin: ^2.0.3
  # 瀑布流插件
  #  flutter_staggered_grid_view: ^0.3.2
  waterfall_flow: ^3.0.1
  #音频处理
#  flutter_sound_lite: '7.4.9+3'
  flutter_audio_recorder2: ^0.0.1
  #音频处理
  audioplayers: ^0.19.0
  #md5
  crypto: ^3.0.1
  convert: ^3.0.0
  # 生成随机UUID字符串
  uuid: ^3.0.4
  # 可自定义拖拽进度条
  flutter_xlider: ^3.4.0
  # 音量监听控制
  volume_watcher: ^2.0.1
  # 解决NestedScroll列表同步的问题
  extended_nested_scroll_view: ^3.0.0
  # 更好的播放器
  better_player: ^0.0.69
  inview_notifier_list: ^2.0.0
  # 绘制扩展 本打算画虚线用的
  # path_drawing: ^0.4.1+1
  # 获取视频的缩略图
  video_thumbnail: ^0.3.3
  # 阻止熄屏
  wakelock: ^0.5.2
  # 联系人样式列表
  azlistview: ^1.1.1
  # 软件包信息
  package_info: ^2.0.2
  # 保存图片视频到相册
  image_gallery_saver: ^1.6.9
  #跳转系统设置
  app_settings: ^4.1.0
  #获取系统通知状态
  notification_permissions: ^0.5.0
  # 网络状态监听
  connectivity: ^3.0.6
  #跳转商店
  launch_review: ^3.0.1
  #打开对应文件安装apk
  open_file: ^3.2.1
  # 高德地图
#  amap_map_fluttify: ^0.30.1
  amap_location_muka: ^0.1.1
  amap_flutter_map: ^2.0.1
  # svg图片
  flutter_svg: 0.22.0
  #可拖拽item list
  reorderables: ^0.4.1
  #扫码
  scan: ^1.4.3
  qr_code_scanner: any
  #二维码生成
  qr_flutter: ^4.0.0
  #url
  url_launcher: ^6.0.6
  #滚轮时间选择器
  flutter_holo_date_picker: ^0.3.4+1
  another_flushbar: ^1.10.23
  #获取文件的MD5
  md5_plugin: ^1.0.2
  #友盟
  umeng_common_sdk: 1.1.0
  #webview
  webview_flutter: ^2.0.8
  #bugly错误收集
  flutter_bugly: ^0.3.2+1
  #极光推送 更新flutter版本后要升级到最新
  jpush_flutter: ^2.1.2



  # 测试用的生成英文单词的库
  english_words: ^4.0.0
  # 测试用从相册或相机获取图片的库
  image_picker: ^0.8.0+1
  #测试用图片放大拖拽
  #  flutter_drag_scale:
  #    git: https://github.com/LiuC520/flutter_drag_scale.git
  #  粘性header
  #  sticky_headers: ^0.1.8+1
  # 测试大图预览
  photo_view: ^0.11.1
  extended_image: ^4.1.0
  # 图像和视频预览组件，支持缩放和拖动
  interactiveviewer_gallery: any
  #  视频编辑器
  #  video_editor: ^ 1.0.3+1
  #  纯Dart的音频/视频/图像选择器，与微信相同，支持多重选择。
  #  wechat_assets_picker


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/emoji.json
    - assets/svg/
    - assets/png/
    - assets/png/2.0x/
    - assets/png/3.0x/
    - images/
    - images/test/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-1.otf
    - family: STHeitiSCMedium
      fonts:
        - asset: assets/fonts/STHeitiSCMedium.ttc
